<?php

namespace App\Exports;

use App\Models\DeploymentExecution;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class DeploymentExecutionsExport implements FromCollection, WithHeadings
{
    public function __construct(private readonly array $filters = [])
    {
    }

    public function collection(): Collection
    {
        $query = DeploymentExecution::query()->with('script');

        if (!empty($this->filters['status'])) {
            $query->where('is_success', $this->filters['status'] === 'success');
        }

        return $query->latest('started_at')->get()->map(function (DeploymentExecution $item): array {
            return [
                'deployment_id' => $item->id,
                'script' => $item->script?->name,
                'started_at' => optional($item->started_at)->toDateTimeString(),
                'finished_at' => optional($item->finished_at)->toDateTimeString(),
                'duration_ms' => $item->duration_ms,
                'status' => $item->is_success ? 'Success' : 'Failed',
                'triggered_by' => $item->triggered_via,
                'exit_code' => $item->exit_code,
                'generated_by' => optional(Auth::user())->username,
                'generated_at' => now()->toDateTimeString(),
            ];
        });
    }

    public function headings(): array
    {
        return [
            'Deployment ID',
            'Script',
            'Started At',
            'Finished At',
            'Duration',
            'Status',
            'Triggered By',
            'Exit Code',
            'Generated By',
            'Generated At',
        ];
    }
}
